# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1782, 856)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(220, 233, 243);")
        self.centralwidget.setObjectName("centralwidget")
        self.button_load_folder = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_folder.setGeometry(QtCore.QRect(10, 14, 200, 140))
        self.button_load_folder.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_load_folder.setObjectName("button_load_folder")
        self.table_files = QtWidgets.QTableWidget(self.centralwidget)
        self.table_files.setGeometry(QtCore.QRect(10, 170, 1761, 641))
        self.table_files.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_files.setObjectName("table_files")
        self.table_files.setColumnCount(0)
        self.table_files.setRowCount(0)
        self.button_output = QtWidgets.QPushButton(self.centralwidget)
        self.button_output.setGeometry(QtCore.QRect(1640, 89, 130, 65))
        self.button_output.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_output.setObjectName("button_output")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(220, 14, 641, 140))
        self.label_info.setStyleSheet("font-family: \'Bahnschrift Condensed\';\n"
"font-size: 25pt;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(48, 105, 176);\n"
"border-radius: 15px;\n"
"padding: 5px;")
        self.label_info.setObjectName("label_info")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(1500, 89, 130, 65))
        self.button_delete.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_delete.setObjectName("button_delete")
        self.button_help = QtWidgets.QPushButton(self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(1500, 14, 130, 65))
        self.button_help.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_help.setObjectName("button_help")
        self.button_clear_cache = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear_cache.setGeometry(QtCore.QRect(1640, 14, 130, 65))
        self.button_clear_cache.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_clear_cache.setObjectName("button_clear_cache")
        self.button_fault_detection = QtWidgets.QPushButton(self.centralwidget)
        self.button_fault_detection.setGeometry(QtCore.QRect(870, 14, 200, 140))
        self.button_fault_detection.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_fault_detection.setObjectName("button_fault_detection")
        self.button_fault_localization = QtWidgets.QPushButton(self.centralwidget)
        self.button_fault_localization.setGeometry(QtCore.QRect(1290, 14, 200, 140))
        self.button_fault_localization.setToolTip("")
        self.button_fault_localization.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_fault_localization.setObjectName("button_fault_localization")
        self.button_fault_identification = QtWidgets.QPushButton(self.centralwidget)
        self.button_fault_identification.setGeometry(QtCore.QRect(1080, 14, 200, 140))
        self.button_fault_identification.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \'Bahnschrift Condensed\';\n"
"background-color: rgb(48, 105, 176);\n"
"border-radius: 16px;")
        self.button_fault_identification.setObjectName("button_fault_identification")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1782, 23))
        self.menubar.setStyleSheet("background-color: rgb(220, 233, 243);")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(220, 233, 243);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_load_folder.setText(_translate("MainWindow", "Load Folder"))
        self.button_output.setText(_translate("MainWindow", "Output"))
        self.label_info.setText(_translate("MainWindow", "Info"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.button_help.setText(_translate("MainWindow", "Help"))
        self.button_clear_cache.setText(_translate("MainWindow", "Clear"))
        self.button_fault_detection.setText(_translate("MainWindow", "Fault\n"
"Detection"))
        self.button_fault_localization.setText(_translate("MainWindow", "Fault\n"
"Localization"))
        self.button_fault_identification.setText(_translate("MainWindow", "Fault\n"
"Identification"))
